overrides:
  ceph:
    conf:
      osd:
        osd_class_load_list: "cephfs hello journal lock log numops rbd refcount 
                              replica_log rgw sdk statelog timeindex user version"
        osd_class_default_list: "cephfs hello journal lock log numops rbd refcount 
                                 replica_log rgw sdk statelog timeindex user version"
tasks:
- workunit:
    clients:
      client.0:
        - cls
