language: c

compiler:
  - gcc
  - clang

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libcunit1-dev
      - libaio-dev
      - libssl-dev

before_script:
  - export MAKEFLAGS="-j$(nproc)"
  - wget http://fast.dpdk.org/rel/dpdk-17.02.tar.xz
  - tar xf dpdk-17.02.tar.xz
  - pushd dpdk-17.02
  - make config T=x86_64-native-linuxapp-$CC
  - sed -i s/CONFIG_RTE_EAL_IGB_UIO=y/CONFIG_RTE_EAL_IGB_UIO=n/ build/.config
  - sed -i s/CONFIG_RTE_KNI_KMOD=y/CONFIG_RTE_KNI_KMOD=n/ build/.config
  - make
  - make install DESTDIR=.
  - export DPDK_DIR=$PWD/usr/local/share/dpdk/x86_64-native-linuxapp-$CC
  - popd

script:
  - make CONFIG_WERROR=y
  - ./unittest.sh
