overrides:
  ceph:
    log-whitelist:
    - but it is still running
    - objects unfound and apparently lost
    conf:
      osd:
        osd debug reject backfill probability: .3
        osd scrub min interval: 60
        osd scrub max interval: 120
        osd max backfills: 3
        osd snap trim sleep: 2
tasks:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgpnum_fix: 1
