
# The task interferes with the network, so we need
# to permit OSDs to complain about that.
overrides:
  ceph:
    log-whitelist:
      - evicting unresponsive client
      - but it is still running
      - slow request

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_client_recovery
