overrides:
  ceph:
    log-whitelist:
      - not responding, replacing
      - \(MDS_INSUFFICIENT_STANDBY\)
tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_failover
