
overrides:
  ceph:
    log-whitelist:
      - bad backtrace on directory inode
      - error reading table object
      - Metadata damage detected
      - slow requests are blocked
      - Behind on trimming

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_journal_repair
