tasks:
- install:
- ceph:
    log-whitelist:
    - slow request
    - .*clock.*skew.*
    - clocks not synchronized
    - overall HEALTH_
    - (MON_CLOCK_SKEW)
- mon_clock_skew_check:
    expect-skew: false
