roles:
- - mon.a
  - mgr.x
  - mds.0
  - osd.0
- - osd.1
  - mon.b
  - client.0
openstack:
  - machine:
      disk: 10 # GB
      ram: 2000 # MB
      cpus: 1
    volumes: # attached to each instance
      count: 2
      size: 10 # GB
tasks:
- ssh_keys:
- print: "**** done ssh_keys"
- ceph-deploy:
- print: "**** done ceph-deploy"
- workunit:
     clients:
        client.0:
           - ceph-tests/ceph-admin-commands.sh
- print: "**** done ceph-tests/ceph-admin-commands.sh"
