meta:
- desc: |
   randomly kill and revive osd
   small chance to increase the number of pgs
overrides:
  ceph:
    log-whitelist:
    - but it is still running
    - objects unfound and apparently lost
    - log bound mismatch
tasks:
- parallel:
    - split_tasks
split_tasks:
  sequential:
    - thrashosds:
        timeout: 1200
        chance_pgnum_grow: 1
        chance_pgpnum_fix: 1
        chance_thrash_cluster_full: 0
        chance_thrash_pg_upmap: 0
        chance_thrash_pg_upmap_items: 0
        chance_force_recovery: 0
    - print: "**** done thrashosds 3-thrash"
