overrides:
  ceph:
    conf:
      client:
        fuse_default_permissions: 0
tasks:
- check-counter:
    counters:
      mds:
        - "mds.dir_split"
- workunit:
    clients:
      all:
        - kernel_untar_build.sh
